createOrReplace

	model Model
		culture: en-US
		defaultPowerBIDataSourceVersion: powerBI_V3
		sourceQueryCulture: en-US
		dataAccessOptions
			legacyRedirects
			returnErrorValuesAsNull

		table MarvelFact
			lineageTag: 743cae73-8a6b-4e03-af99-d194d47d16af

			measure 'Number of Characters' = ```
					COUNTROWS('MarvelFact') + 1000
					
					```
				formatString: 0
				lineageTag: df54ac01-57f7-4a28-a338-2609c59c6503

			measure 'Number of Characters Title By Date' = "Number of Characters that first appeared " & [Date Filter]
				lineageTag: 69d792e2-4fcc-4491-9f87-3ddb00d7bbbc

			measure 'Rank of Appearances' = ```
								
								RANKX (
					    ALLEXCEPT ( 'MarvelFact', AlignmentDim[Alignment] ),
					    CALCULATE ( SUM ( 'MarvelFact'[Appearances] ) )
					)
								
					```
				formatString: 0
				lineageTag: 714f1b79-a4f3-4a84-a723-7b62d9467ba9

			measure 'Running Total of Character Appearances' = ```
					
					CALCULATE (COUNTROWS ( 'MarvelFact' ),
					    FILTER (ALL ( 'MarvelFact' ),
					        'MarvelFact'[DateID] <= MAX ( 'DateDim'[DateID] ))
					)
					
					```
				formatString: #,0
				lineageTag: 7fb56eb7-be01-4955-92db-9dab09d95a7a

			column ID
				dataType: int64
				formatString: 0
				lineageTag: b7ff624e-3f51-4955-89fb-6129a2da0110
				summarizeBy: count
				sourceColumn: ID

				annotation SummarizationSetBy = Automatic

			column Name
				dataType: string
				lineageTag: babc8e7f-21c5-43d2-b7f3-f871a5275156
				summarizeBy: none
				sourceColumn: Name

				annotation SummarizationSetBy = Automatic

			column Appearances
				dataType: int64
				formatString: #,0
				lineageTag: 1eaca556-a316-4132-bec0-1e10537e8c5a
				summarizeBy: sum
				sourceColumn: Appearances

				annotation SummarizationSetBy = Automatic

			column DateID
				dataType: int64
				formatString: 0
				lineageTag: 5a5e1b5e-96a3-43c5-bfa1-dbf397dbe6dc
				summarizeBy: none
				sourceColumn: DateID

				annotation SummarizationSetBy = Automatic

			column EyeID
				dataType: int64
				formatString: 0
				lineageTag: e91d9d2a-fc21-45d6-b9a4-562098b146d3
				summarizeBy: none
				sourceColumn: EyeID

				annotation SummarizationSetBy = Automatic

			column AlignmentID
				dataType: int64
				formatString: 0
				lineageTag: 6cdf4368-853c-471f-8092-72f8e6ef6b29
				summarizeBy: none
				sourceColumn: AlignmentID

				annotation SummarizationSetBy = Automatic

			column 'Test Change' = 1
				dataType: dateTime
				formatString: Long Time
				lineageTag: 48b215f3-6230-4672-ae9f-8133298d5615
				summarizeBy: none

				changedProperty = DataType

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Time

			partition MarvelFact-6bd788f7-6397-4a40-bbcd-b7a7355b7188 = m
				mode: import
				queryGroup: Fact
				source =
						let
						    Source = MarvelSource,
						    #"Changed Type" = Table.TransformColumnTypes(Source,{{"page_id", Int64.Type}, {"name", type text}, {"urlslug", type text}, {"ID", type text}, {"ALIGN", type text}, {"EYE", type text}, {"HAIR", type text}, {"SEX", type text}, {"GSM", type text}, {"ALIVE", type text}, {"APPEARANCES", Int64.Type}, {"FIRST APPEARANCE", type text}, {"Year", Int64.Type}}),
						    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "FIRST APPEARANCE", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"FIRST APPEARANCE.1", "FIRST APPEARANCE.2"}),
						    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"FIRST APPEARANCE.1", type text}, {"FIRST APPEARANCE.2", Int64.Type}}),
						    #"Added Custom" = Table.AddColumn(#"Changed Type1", "DateKey", each [FIRST APPEARANCE.1]&"-"&Text.From([Year])),
						    #"Replaced Value" = Table.ReplaceValue(#"Added Custom",null,"Jan-0001",Replacer.ReplaceValue,{"DateKey"}),
						    #"Removed Columns" = Table.RemoveColumns(#"Replaced Value",{"FIRST APPEARANCE.1", "FIRST APPEARANCE.2", "Year"}),
						    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"DateKey"}, DateDim, {"DateKey"}, "DateDim", JoinKind.LeftOuter),
						    #"Expanded DateDim" = Table.ExpandTableColumn(#"Merged Queries", "DateDim", {"DateID"}, {"DateDim.DateID"}),
						    #"Removed Columns1" = Table.RemoveColumns(#"Expanded DateDim",{"DateKey"}),
						    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns1",{{"DateDim.DateID", "DateID"}}),
						    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns",{"SEX", "GSM", "ALIVE", "urlslug"}),
						    #"Merged Queries1" = Table.NestedJoin(#"Removed Columns2", {"EYE"}, EyeColorDim, {"EyeKey"}, "EyeColorDim", JoinKind.LeftOuter),
						    #"Expanded EyeColorDim" = Table.ExpandTableColumn(#"Merged Queries1", "EyeColorDim", {"EyeID"}, {"EyeID"}),
						    #"Removed Columns3" = Table.RemoveColumns(#"Expanded EyeColorDim",{"HAIR"}),
						    #"Merged Queries2" = Table.NestedJoin(#"Removed Columns3", {"ALIGN"}, AlignmentDim, {"AlignmentKey"}, "AlignmentDim", JoinKind.LeftOuter),
						    #"Expanded AlignmentDim" = Table.ExpandTableColumn(#"Merged Queries2", "AlignmentDim", {"AlignmentID"}, {"AlignmentID"}),
						    #"Removed Columns4" = Table.RemoveColumns(#"Expanded AlignmentDim",{"ID", "ALIGN", "EYE"}),
						    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns4",{{"name", "Name"}, {"APPEARANCES", "Appearances"}, {"page_id", "ID"}})
						in
						    #"Renamed Columns1"

			annotation PBI_ResultType = Table

			annotation PBI_NavigationStepName = Navigation

		table DateDim
			lineageTag: 864aaed1-9b52-4c91-a679-eee5e9ce61ea

			measure 'Date Filter' = ```
					
					VAR MinDate =
					    FORMAT ( MIN ( 'DateDim'[Date] ), "MMMM, YYYY" )
					VAR MaxDate =
					    FORMAT ( MAX ( 'DateDim'[Date] ), "MMMM, YYYY" )
					VAR SelDate =
					    SELECTEDVALUE ( 'DateDim'[Date], "X" )
					RETURN
					    IF (
					        SelDate = "X",
					        "between " & MinDate & " and " & MaxDate,
					        "for the month of " & FORMAT ( SelDate, "MMMM, YYYY" )
					    )
					
					```
				lineageTag: 4a102139-aa1e-4805-8ff3-8f26cc11ca77

			column DateID
				dataType: int64
				isKey
				formatString: 0
				lineageTag: f04165d7-a964-463a-9fe1-11c45e755a75
				summarizeBy: none
				sourceColumn: DateID

				annotation SummarizationSetBy = Automatic

			column Date
				dataType: dateTime
				formatString: Long Date
				lineageTag: 1f5eadd5-60fa-4976-a5ef-a7abd80457b5
				summarizeBy: none
				sourceColumn: Date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column DateKey
				dataType: string
				lineageTag: 99cbf526-ec1a-4670-b1ef-873cddd7efaa
				summarizeBy: none
				sourceColumn: DateKey

				annotation SummarizationSetBy = Automatic

			column MonthYearSort
				dataType: int64
				formatString: 0
				lineageTag: d0061923-ebd6-4cfd-be33-d910d8d0714f
				summarizeBy: none
				sourceColumn: MonthYearSort

				changedProperty = DataType

				annotation SummarizationSetBy = Automatic

			column 'Month Year' = IF([DateID]<>0,FORMAT([Date],"MMM-YY"),"Not Available")
				lineageTag: 022b9561-6f1d-432a-927a-b431bbcc5cff
				summarizeBy: none
				sortByColumn: MonthYearSort

				annotation SummarizationSetBy = Automatic

			column Year
				dataType: int64
				formatString: 0
				lineageTag: 526e727b-b599-42fa-9aba-ff2c64b6c7df
				summarizeBy: none
				sourceColumn: Year

				annotation SummarizationSetBy = Automatic

			partition DateDim-e3a1d953-1356-4aad-8dfb-22648d5b0c23 = m
				mode: import
				queryGroup: Dimensions
				source =
						let
						    Source = MarvelSource,
						    #"Removed Other Columns" = Table.SelectColumns(Source,{"FIRST APPEARANCE", "Year"}),
						    #"Split Column by Delimiter" = Table.SplitColumn(#"Removed Other Columns", "FIRST APPEARANCE", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"FIRST APPEARANCE.1", "FIRST APPEARANCE.2"}),
						    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"FIRST APPEARANCE.1", type text}, {"FIRST APPEARANCE.2", Int64.Type}}),
						    #"Added Custom" = Table.AddColumn(#"Changed Type1", "Date", each Date.FromText([FIRST APPEARANCE.1]&" 1, "&Text.From([Year]))),
						    #"Filtered Rows" = Table.SelectRows(#"Added Custom", each ([Date] <> null)),
						    #"Sorted Rows" = Table.Sort(#"Filtered Rows",{{"Date", Order.Ascending}}),
						    #"Removed Columns" = Table.RemoveColumns(#"Sorted Rows",{"FIRST APPEARANCE.1", "FIRST APPEARANCE.2", "Year"}),
						    #"Added Custom1" = Table.AddColumn(#"Removed Columns", "EndDate", each Date.From(DateTime.LocalNow())),
						    #"Filtered Rows1" = Table.SelectRows(#"Added Custom1", let earliest = List.Min(#"Added Custom1"[Date]) in each [Date] = earliest),
						    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows1", {"Date"}),
						    #"Renamed Columns" = Table.RenameColumns(#"Removed Duplicates",{{"Date", "StartDate"}}),
						    #"Added Custom2" = Table.AddColumn(#"Renamed Columns", "Dates", each {Number.From([StartDate])..Number.From([EndDate])}),
						    #"Expanded Dates" = Table.ExpandListColumn(#"Added Custom2", "Dates"),
						    #"Changed Type2" = Table.TransformColumnTypes(#"Expanded Dates",{{"Dates", type date}}),
						    #"Filter1stMonth" = Table.SelectRows(#"Changed Type2", each Date.Day([Dates]) = 1),
						    #"Removed Columns1" = Table.RemoveColumns(#"Filter1stMonth",{"StartDate", "EndDate"}),
						    #"Added Index" = Table.AddIndexColumn(#"Removed Columns1", "Index", 1, 1, Int64.Type),
						    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Dates"}),
						    #"Added Custom3" = Table.AddColumn(#"Reordered Columns", "DateKey", each Date.ToText([Dates],"MMM-yyyy")),
						    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom3",{{"Dates", "Date"}, {"Index", "DateID"}}),
						    #"Appended Query" = Table.Combine({#"Renamed Columns1", DateDimBlank}),
						    #"Sorted Rows1" = Table.Sort(#"Appended Query",{{"DateID", Order.Ascending}}),
						    #"Replaced Value" = Table.ReplaceValue(#"Sorted Rows1","","Jan-0001",Replacer.ReplaceValue,{"DateKey"}),
						    #"Added Custom4" = Table.AddColumn(#"Replaced Value", "MonthYearSort", each Date.Year([Date])*100 + Date.Month([Date])),
						    #"Added Custom5" = Table.AddColumn(#"Added Custom4", "Year", each Date.Year([Date])),
						    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom5",{{"Year", Int64.Type}})
						in
						    #"Changed Type"

			annotation PBI_ResultType = Table

			annotation PBI_NavigationStepName = Navigation

		table EyeColorDim
			lineageTag: 037f7bba-4826-403f-b77b-fb781709cca3

			column EyeID
				dataType: int64
				formatString: 0
				lineageTag: 997fc90c-3966-4e04-9b0a-4890e6bb2aa2
				summarizeBy: none
				sourceColumn: EyeID

				annotation SummarizationSetBy = Automatic

			column EyeKey
				dataType: string
				lineageTag: 55a30476-3ae6-4781-999b-ef1816fb31d9
				summarizeBy: none
				sourceColumn: EyeKey

				annotation SummarizationSetBy = Automatic

			column 'Eye Color'
				dataType: string
				lineageTag: ebbc7a88-ab18-435c-9c89-435151873c5c
				summarizeBy: none
				sourceColumn: Eye Color

				annotation SummarizationSetBy = Automatic

			partition EyeColorDim-9e3c8afc-012c-44ec-9c61-96893c06fa7b = m
				mode: import
				queryGroup: Dimensions
				source =
						let
						    Source = MarvelSource,
						    #"Removed Other Columns" = Table.SelectColumns(Source,{"EYE"}),
						    #"Duplicated Column" = Table.DuplicateColumn(#"Removed Other Columns", "EYE", "EYE - Copy"),
						    #"Removed Duplicates" = Table.Distinct(#"Duplicated Column", {"EYE"}),
						    #"Renamed Columns" = Table.RenameColumns(#"Removed Duplicates",{{"EYE", "EyeKey"}}),
						    #"Split Column by Delimiter" = Table.SplitColumn(#"Renamed Columns", "EYE - Copy", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"EYE - Copy.1", "EYE - Copy.2"}),
						    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"EYE - Copy.1", type text}, {"EYE - Copy.2", type text}}),
						    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"EYE - Copy.2"}),
						    #"Sorted Rows" = Table.Sort(#"Removed Columns",{{"EYE - Copy.1", Order.Ascending}}),
						    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 0, 1, Int64.Type),
						    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "EyeKey", "EYE - Copy.1"}),
						    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns",{{"Index", "EyeID"}, {"EYE - Copy.1", "Eye Color"}}),
						    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1","","Not Available",Replacer.ReplaceValue,{"Eye Color"})
						in
						    #"Replaced Value"

			annotation PBI_ResultType = Table

		table MarvelSource
			isHidden
			lineageTag: 1398ee0f-272b-4a82-a465-0ad3a9527f05

			column page_id
				dataType: int64
				isHidden
				formatString: 0
				lineageTag: 90efbd2f-4c8e-4802-9c30-8a365e8386ad
				summarizeBy: sum
				sourceColumn: page_id

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column name
				dataType: string
				isHidden
				lineageTag: f2c44bae-5db7-41fc-a456-49eff0d7444d
				summarizeBy: none
				sourceColumn: name

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column urlslug
				dataType: string
				isHidden
				lineageTag: 1d36baa2-4bea-4ab5-9cc1-4bb760a78c37
				summarizeBy: none
				sourceColumn: urlslug

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column ID
				dataType: string
				isHidden
				lineageTag: caa99830-9bba-472c-afd6-22222592549a
				summarizeBy: none
				sourceColumn: ID

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column ALIGN
				dataType: string
				isHidden
				lineageTag: 0f7a14b4-c795-44cb-a3d4-9dcfc091ac3f
				summarizeBy: none
				sourceColumn: ALIGN

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column EYE
				dataType: string
				isHidden
				lineageTag: 20d4352e-62ac-46b2-a5e8-052180eded7e
				summarizeBy: none
				sourceColumn: EYE

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column HAIR
				dataType: string
				isHidden
				lineageTag: ea60ac25-df49-4c18-b092-846a7f4c17b2
				summarizeBy: none
				sourceColumn: HAIR

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column SEX
				dataType: string
				isHidden
				lineageTag: 7bffbbad-78b7-4f16-9bca-111612f54300
				summarizeBy: none
				sourceColumn: SEX

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column GSM
				dataType: string
				isHidden
				lineageTag: 55c8d845-32d9-44fe-88c9-44a680eeafac
				summarizeBy: none
				sourceColumn: GSM

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column ALIVE
				dataType: string
				isHidden
				lineageTag: a6b3d8cc-9410-460c-891e-25e80b772693
				summarizeBy: none
				sourceColumn: ALIVE

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column APPEARANCES
				dataType: int64
				isHidden
				formatString: 0
				lineageTag: 402cfdd7-08ab-478e-a039-d3abc7f0841c
				summarizeBy: sum
				sourceColumn: APPEARANCES

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column 'FIRST APPEARANCE'
				dataType: string
				isHidden
				lineageTag: 7e67c78a-607b-4a89-9b09-5ada2a2581f0
				summarizeBy: none
				sourceColumn: FIRST APPEARANCE

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column Year
				dataType: int64
				isHidden
				formatString: 0
				lineageTag: 1ed89e36-864d-414c-9d19-afb0e40a72f1
				summarizeBy: sum
				sourceColumn: Year

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			partition MarvelSource-9b980f40-8504-413c-98b2-7be27f4146c9 = m
				mode: import
				source =
						let
						    Source = Csv.Document(Web.Contents(WebURL),[Delimiter=",", Columns=13, Encoding=65001, QuoteStyle=QuoteStyle.None]),
						    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
						    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"page_id", Int64.Type}, {"name", type text}, {"urlslug", type text}, {"ID", type text}, {"ALIGN", type text}, {"EYE", type text}, {"HAIR", type text}, {"SEX", type text}, {"GSM", type text}, {"ALIVE", type text}, {"APPEARANCES", Int64.Type}, {"FIRST APPEARANCE", type text}, {"Year", Int64.Type}})
						in
						    #"Changed Type"

			annotation PBI_ResultType = Table

		table AlignmentDim
			lineageTag: bfdfe08d-e2c6-4102-a232-3c7c68b03669

			column AlignmentID
				dataType: int64
				formatString: 0
				lineageTag: 5fe32fbe-cb3d-4291-909d-05db95b3f299
				summarizeBy: none
				sourceColumn: AlignmentID

				annotation SummarizationSetBy = Automatic

			column Alignment
				dataType: string
				lineageTag: 0911cc1e-86b5-4fd7-b8ad-ff20a910f842
				summarizeBy: none
				sourceColumn: Alignment

				annotation SummarizationSetBy = Automatic

			column AlignmentKey
				dataType: string
				lineageTag: d3157c54-4773-49c6-b33b-6c8583855468
				summarizeBy: none
				sourceColumn: AlignmentKey

				annotation SummarizationSetBy = Automatic

			partition AlignmentDim-efd4d92e-b9f5-41bd-a54f-2260dec05954 = m
				mode: import
				queryGroup: Dimensions
				source =
						let
						    Source = MarvelSource,
						    #"Removed Other Columns" = Table.SelectColumns(Source,{"ALIGN"}),
						    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
						    #"Duplicated Column" = Table.DuplicateColumn(#"Removed Duplicates", "ALIGN", "ALIGN - Copy"),
						    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"ALIGN - Copy", "AlignmentKey"}}),
						    #"Split Column by Delimiter" = Table.SplitColumn(#"Renamed Columns", "ALIGN", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"ALIGN.1", "ALIGN.2"}),
						    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"ALIGN.1", type text}, {"ALIGN.2", type text}}),
						    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type",{{"ALIGN.1", "Alignment"}}),
						    #"Sorted Rows" = Table.Sort(#"Renamed Columns1",{{"Alignment", Order.Ascending}}),
						    #"Replaced Value" = Table.ReplaceValue(#"Sorted Rows","","Not Available",Replacer.ReplaceValue,{"Alignment"}),
						    #"Added Index" = Table.AddIndexColumn(#"Replaced Value", "Index", 0, 1, Int64.Type),
						    #"Renamed Columns2" = Table.RenameColumns(#"Added Index",{{"Index", "AlignmentID"}}),
						    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns2",{"AlignmentID", "Alignment", "ALIGN.2", "AlignmentKey"}),
						    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"ALIGN.2"}),
						    #"Renamed Columns3" = Table.RenameColumns(#"Removed Columns",{{"AlignmentKey", "AlignmentKey"}}),
						    #"Sorted Rows1" = Table.Sort(#"Renamed Columns3",{{"AlignmentKey", Order.Ascending}})
						in
						    #"Sorted Rows1"

			annotation PBI_ResultType = Table

			annotation PBI_NavigationStepName = Navigation

		table DataTypes
			lineageTag: 7f69575d-04de-4b21-8397-70fa031cdead

			column 'Whole Number'
				dataType: int64
				formatString: 0
				lineageTag: 0f9bab8a-c892-4ff5-8ff3-95d4387d1e8a
				summarizeBy: sum
				sourceColumn: Whole Number

				annotation SummarizationSetBy = Automatic

			column 'Decimal Number'
				dataType: double
				lineageTag: 7536a752-6b53-484c-9f5a-3ffec4e7cad0
				summarizeBy: sum
				sourceColumn: Decimal Number

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column Boolean
				dataType: boolean
				formatString: """TRUE"";""TRUE"";""FALSE"""
				lineageTag: 0a6241d6-eba0-43c1-b18b-164075811fac
				summarizeBy: none
				sourceColumn: Boolean

				annotation SummarizationSetBy = Automatic

			column Text
				dataType: string
				lineageTag: 9c5b6fcd-85af-4efd-97c5-2a6039698a4b
				summarizeBy: none
				sourceColumn: Text

				annotation SummarizationSetBy = Automatic

			column Date
				dataType: dateTime
				formatString: Long Date
				lineageTag: 9b5893c4-1bae-41ea-9259-9c71aa2fa810
				summarizeBy: none
				sourceColumn: Date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column Currency
				dataType: decimal
				formatString: \$#,0.00;(\$#,0.00);\$#,0.00
				lineageTag: 8de8e7c5-4c39-4bf7-b725-059c868868da
				summarizeBy: sum
				sourceColumn: Currency

				changedProperty = DataType

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"currencyCulture":"en-US"}

			partition DataTypes = m
				mode: import
				source =
						let
						    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUTLUMzIGUiFFpakgKiOzWAGISlIrSkCS+ob6RgZGJmB1lpZKsbEA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Whole Number" = _t, #"Decimal Number" = _t, Boolean = _t, Text = _t, Date = _t, Currency = _t]),
						    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Whole Number", Int64.Type}, {"Decimal Number", type number}, {"Boolean", type logical}, {"Text", type text}, {"Date", type date}, {"Currency", type number}})
						in
						    #"Changed Type"

			annotation PBI_ResultType = Table

		relationship c536afe1-3f60-4922-8aaa-c9e5754c7744
			fromColumn: MarvelFact.DateID
			toColumn: DateDim.DateID

		relationship 99b81a18-76e8-4806-a3e6-d8ab605cc07a
			fromColumn: MarvelFact.EyeID
			toColumn: EyeColorDim.EyeID

		relationship 56999b72-f4f6-442c-9f2d-65422acff5af
			fromColumn: MarvelFact.AlignmentID
			toColumn: AlignmentDim.AlignmentID

		cultureInfo en-US

			linguisticMetadata =
					{
					  "Version": "1.0.0",
					  "Language": "en-US"
					}
				contentType: json

		expression DateDimBlank =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlDSUfJKzNM1MDAwBDIN9Q31wczYWAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [DateID = _t, DateKey = _t, Date = _t]),
				    #"Changed Type1" = Table.TransformColumnTypes(Source,{{"Date", type date}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type1",{{"DateID", Int64.Type}, {"DateKey", type text}, {"Date", type date}})
				in
				    #"Changed Type"
			lineageTag: e21359d2-597d-431f-a09b-cc69a3ccf63e

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		/// Use: https://raw.githubusercontent.com/fivethirtyeight/data/master/comic-characters/marvel-wikia-data.csv
		expression WebURL = "https://raw.githubusercontent.com/fivethirtyeight/data/master/comic-characters/marvel-wikia-data.csv" meta [IsParameterQuery=true, Type="Any", IsParameterQueryRequired=true]
			lineageTag: 82d1cfde-eee7-4ae8-9d6e-4e2d1c4d13b5
			queryGroup: Parameters

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Text

		queryGroup Dimensions

			annotation PBI_QueryGroupOrder = 0

		queryGroup Fact

			annotation PBI_QueryGroupOrder = 1

		queryGroup Parameters

			annotation PBI_QueryGroupOrder = 2

		annotation PBIDesktopVersion = 2.143.878.0 (25.05)+b20aa3b866ec1b70879135a4e60e4b1301c75b21

		annotation PBI_QueryOrder = ["MarvelFact","DateDim","EyeColorDim","AlignmentDim","DateDimBlank","MarvelSource","WebURL","DataTypes"]

		annotation __PBI_TimeIntelligenceEnabled = 0

		annotation PBI_ProTooling = ["DevMode","DaxQueryView_Desktop","DaxCopilot_Change_Accepted_In_Desktop"]

